default:
	gcc -g -o prog main.c time.c listArrayList.c listElem.c mapElem.c mapArrayList.c stringCode.c utils.c input.c flight.c airport.c airline.c baseCommands.c indicatorCommands.c -lm
clean:
	rm -f prog
run:
	./prog